  apiVersion: v1
  kind: ReplicationController
  metadata:
    name: php7-fpm
  spec:
    replicas: 1
    selector:
      app: php7-fpm
    template:
      metadata:
        name: php7-fpm
        labels:
          app: php7-fpm
      spec:
        containers:
        - name: phpfpm
          image: robkel/php7-fpm
          ports:
          - containerPort: 9000